/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GranEmpresa.Productos;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author JenniferB
 */
public class ModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProducto
     */
    Connection sesion;
    //VARIABLES PARA LOS CAMPOS DE "Medidas"
    DefaultComboBoxModel ModeloMed = new DefaultComboBoxModel();
    String ClaveMed;
    String DescMed;
    
    //VARIABLES PARA LOS CAMPOS DE "Categorias"
    DefaultComboBoxModel ModeloCat = new DefaultComboBoxModel();
    String ClaveCat;
    String NombreCat;
    
    //VARIABLES PARA LOS CAMPOS DE "Proveedores"
    DefaultComboBoxModel ModeloProv = new DefaultComboBoxModel();
    String ClaveProv;
    String NombreProv;
    String Domicilio;
    String CURP;
    String RFC;
    String Tel;
    String Correo;
    String PWeb;
    
    //VARIABLES PARA LOS CAMPOS DE "Productos"
    DefaultComboBoxModel ModeloProd = new DefaultComboBoxModel();
    String ClaveProd;
    String NombreProd;
    String DescProd;
    float PrecioProd;
    int CantProd;
    
    public ModificarProducto() {
        initComponents();
        try{
            sesion=DriverManager.getConnection("jdbc:odbc:conectar");
            Statement sel= sesion.createStatement();
            //Cargar en el los datos en el ComboBox de medidas
            ResultSet rpt= sel.executeQuery("SELECT * FROM Medidas");
            while(rpt.next()){
               ClaveMed=rpt.getString(1);
               DescMed=rpt.getString(2);
               ModeloMed.addElement(DescMed);
            }
            rpt.close();
            medida.setModel(ModeloMed);
            
            //Cargar en el los datos en el ComboBox de Categorías
            rpt= sel.executeQuery("SELECT * FROM Categorias");
            while(rpt.next()){
               ClaveCat=rpt.getString(1);
               NombreCat=rpt.getString(2);
               ModeloCat.addElement(NombreCat);
            }
            rpt.close();
            categoria.setModel(ModeloCat);
        
            //Cargar en el los datos en el ComboBox de Proveedores
            rpt= sel.executeQuery("SELECT * FROM Proveedores");
            while(rpt.next()){
               ClaveProv=rpt.getString(1);
               NombreProv=rpt.getString(2);
               Domicilio=rpt.getString(3);
               CURP=rpt.getString(4);
               RFC=rpt.getString(5);
               Tel=rpt.getString(6);
               Correo=rpt.getString(7);
               PWeb=rpt.getString(8);
               ModeloProv.addElement(NombreProv);
            }
            rpt.close();
            proveedor.setModel(ModeloProv);
            
            rpt= sel.executeQuery("SELECT * FROM Productos WHERE ClaveProdCat='"+Productos.ClaveProdActual+"'");
            rpt.next();
            ClaveProd=rpt.getString(1);
            NombreProd=rpt.getString(2);
            DescProd=rpt.getString(3);
            PrecioProd=rpt.getFloat(4);
            CantProd=rpt.getInt(5);
            rpt.close();
            
            nombre.setText(NombreProd);
            descripcion.setText(DescProd);
            precio.setText(Float.toString(PrecioProd));
            cantidad.setValue(CantProd);
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "ERROR AL OBTENER DATOS DE LOS PRODUCTOS");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        cantidad = new javax.swing.JSpinner();
        medida = new javax.swing.JComboBox();
        categoria = new javax.swing.JComboBox();
        proveedor = new javax.swing.JComboBox();
        guardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Modificar Producto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Precio Unitario:   $");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Cantidad:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Medida:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Categoría:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Proveedor:");

        cantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        medida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Ninguno>" }));

        categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Ninguno>" }));

        proveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Ninguno>" }));

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/1363051449_3floppy_unmount.png"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/regresar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantidad)
                            .addComponent(medida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precio))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(82, 82, 82)
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
         if ("".equals(nombre.getText())){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
            nombre.requestFocus();
        }else if ("".equals(descripcion.getText())){
            JOptionPane.showMessageDialog(this, "Debe ingresar una descripciÃ³n");
            descripcion.requestFocus();
        }else if ("".equals(precio.getText())){
            JOptionPane.showMessageDialog(this, "Debe ingresar el precio");
            precio.requestFocus();
        }else if (medida.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this, "Debe elegir una unidad de medida");
            medida.requestFocus();
        }else if (categoria.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this, "Debe elegir una categorÃ­a");
            categoria.requestFocus();
        }else if (proveedor.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this, "Debe elegir a un proveedor");
            proveedor.requestFocus();
        }else{
            try{
                sesion=DriverManager.getConnection("jdbc:odbc:conectar");
                Statement sel= sesion.createStatement();
                
                ResultSet rpt= sel.executeQuery("SELECT * FROM Medidas WHERE Descripcion='"+(medida.getSelectedItem()).toString()+"'");
                rpt.next();
                ClaveMed=rpt.getString(1);
                rpt.close();
                        
                rpt= sel.executeQuery("SELECT * FROM Categorias WHERE Nombre='"+(categoria.getSelectedItem()).toString()+"'");
                rpt.next();
                ClaveCat=rpt.getString(1);
                rpt.close();
                
                rpt= sel.executeQuery("SELECT * FROM Proveedores WHERE Nombre='"+(proveedor.getSelectedItem()).toString()+"'");
                rpt.next();
                ClaveProv=rpt.getString(1);
                rpt.close();
                
                rpt= sel.executeQuery("UPDATE Productos"
                        + " SET ClaveProd='"+ClaveProd+"'"
                        + ", Nombre='"+nombre.getText()+"'"
                        + ", Descripcion='"+descripcion.getText()+"'"
                        + ", Precio="+Float.parseFloat(precio.getText())+""
                        + ", Cantidad="+Integer.parseInt(cantidad.getValue().toString())+""
                        + ", ClaveMed='"+ClaveMed+"'"
                        + ", ClaveCat='"+ClaveCat+"'"
                        + ", ClaveProv='"+ClaveProv+"'"
                        + ", ClaveProdCat='"+ClaveCat+"-"+ClaveProd+"'"
                        + " WHERE ClaveProdCat='"+Productos.ClaveProdActual+"'");
                rpt.next();
                rpt.close();
                
                
                JOptionPane.showMessageDialog(this, "Los datos han sido modificados exitosamente");
                this.hide();
                new Productos().show();
            }
            catch(SQLException e){
                this.hide();
                new Productos().show();
            }
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        new Productos().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProducto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner cantidad;
    private javax.swing.JComboBox categoria;
    private javax.swing.JTextField descripcion;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox medida;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JComboBox proveedor;
    // End of variables declaration//GEN-END:variables
}
