/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GranEmpresa.Productos;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author JenniferB
 */
public class NuevoProducto extends javax.swing.JFrame {

    /**
     * Creates new form nuevoConcepto
     */
    Connection sesion;
    //VARIABLES PARA LOS CAMPOS DE "Medidas"
    DefaultComboBoxModel ModeloMed = new DefaultComboBoxModel();
    String ClaveMed;
    String DescMed;
    
    //VARIABLES PARA LOS CAMPOS DE "Categorias"
    DefaultComboBoxModel ModeloCat = new DefaultComboBoxModel();
    String ClaveCat;
    String NombreCat;
    
    //VARIABLES PARA LOS CAMPOS DE "Proveedores"
    DefaultComboBoxModel ModeloProv = new DefaultComboBoxModel();
    String ClaveProv;
    String NombreProv;
    String Domicilio;
    String CURP;
    String RFC;
    String Tel;
    String Correo;
    String PWeb;
    
    public NuevoProducto() {
        initComponents();
        try{
            sesion=DriverManager.getConnection("jdbc:odbc:conectar");
            Statement sel= sesion.createStatement();
            //Cargar en el los datos en el ComboBox de medidas
            ResultSet rpt= sel.executeQuery("SELECT * FROM Medidas");
            while(rpt.next()){
               ClaveMed=rpt.getString(1);
               DescMed=rpt.getString(2);
               ModeloMed.addElement(DescMed);
            }
            rpt.close();
            medida.setModel(ModeloMed);
            
            //Cargar en el los datos en el ComboBox de Categorías
            rpt= sel.executeQuery("SELECT * FROM Categorias");
            while(rpt.next()){
               ClaveCat=rpt.getString(1);
               NombreCat=rpt.getString(2);
               ModeloCat.addElement(NombreCat);
            }
            rpt.close();
            categoria.setModel(ModeloCat);
        
            //Cargar en el los datos en el ComboBox de Proveedores
            rpt= sel.executeQuery("SELECT * FROM Proveedores");
            while(rpt.next()){
               ClaveProv=rpt.getString(1);
               NombreProv=rpt.getString(2);
               Domicilio=rpt.getString(3);
               CURP=rpt.getString(4);
               RFC=rpt.getString(5);
               Tel=rpt.getString(6);
               Correo=rpt.getString(7);
               PWeb=rpt.getString(8);
               ModeloProv.addElement(NombreProv);
            }
            rpt.close();
            proveedor.setModel(ModeloProv);
        
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "ERROR AL OBTENER DATOS DE LOS PRODUCTOS");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Guardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        descripcion = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        medida = new javax.swing.JComboBox();
        categoria = new javax.swing.JComboBox();
        proveedor = new javax.swing.JComboBox();
        cantidad = new javax.swing.JSpinner();
        regresar = new javax.swing.JButton();

        Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/1363051449_3floppy_unmount.png"))); // NOI18N
        Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Nuevo Producto");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setLabelFor(nombre);
        jLabel1.setText("Nombre:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setLabelFor(descripcion);
        jLabel10.setText("Descripción:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setLabelFor(precio);
        jLabel11.setText("Precio Unitario:   $");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setLabelFor(cantidad);
        jLabel12.setText("Cantidad:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setLabelFor(medida);
        jLabel13.setText("Medida:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setLabelFor(categoria);
        jLabel14.setText("Categoría:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setLabelFor(proveedor);
        jLabel15.setText("Proveedor:");

        nombre.setToolTipText("");

        descripcion.setToolTipText("");

        precio.setToolTipText("");

        medida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Ninguno>" }));

        categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Ninguno>" }));

        proveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Ninguno>" }));

        cantidad.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/regresar.png"))); // NOI18N
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(medida, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
      //Validación del formulario
        if ("".equals(nombre.getText())){
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
            nombre.requestFocus();
        }else if ("".equals(descripcion.getText())){
            JOptionPane.showMessageDialog(this, "Debe ingresar una descripción");
            descripcion.requestFocus();
        }else if ("".equals(precio.getText())){
            JOptionPane.showMessageDialog(this, "Debe ingresar el precio");
            precio.requestFocus();
        }else if (medida.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this, "Debe elegir una unidad de medida");
            medida.requestFocus();
        }else if (categoria.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this, "Debe elegir una categoría");
            categoria.requestFocus();
        }else if (proveedor.getSelectedIndex()<0){
            JOptionPane.showMessageDialog(this, "Debe elegir a un proveedor");
            proveedor.requestFocus();
        }else{
           
            try{
                sesion=DriverManager.getConnection("jdbc:odbc:conectar");
                Statement sel= sesion.createStatement();
                //Buscar los datos de los ComboBox seleccionados
                ResultSet rpt= sel.executeQuery("SELECT * FROM Medidas WHERE Descripcion='"+(medida.getSelectedItem()).toString()+"'");
                rpt.next();
                ClaveMed=rpt.getString(1);
                rpt.close();
                        
                rpt= sel.executeQuery("SELECT * FROM Categorias WHERE Nombre='"+(categoria.getSelectedItem()).toString()+"'");
                rpt.next();
                ClaveCat=rpt.getString(1);
                rpt.close();
                
                rpt= sel.executeQuery("SELECT * FROM Proveedores WHERE Nombre='"+(proveedor.getSelectedItem()).toString()+"'");
                rpt.next();
                ClaveProv=rpt.getString(1);
                rpt.close();
                
                //Obtener el último producto
                int ClaveProd=0;
                rpt= sel.executeQuery("SELECT * FROM Productos");
                while(rpt.next()){
                    ClaveProd=rpt.getInt(1);
                }
                ClaveProd=ClaveProd+1;
                rpt.close();
                
                String ClaveProdCat=ClaveCat+"-"+Integer.toString(ClaveProd);
                
                rpt= sel.executeQuery("INSERT INTO Productos VALUES('"+Integer.toString(ClaveProd)+"','"+nombre.getText()+"','"+descripcion.getText()+"',"+Float.parseFloat(precio.getText())+","+Integer.parseInt(cantidad.getValue().toString())+",'"+ClaveProv+"','"+ClaveMed+"','"+ClaveCat+"','"+ClaveProdCat+"')");
                rpt.close();   
                JOptionPane.showMessageDialog(this, "Los datos han sido guardados exitosamente");
                this.hide();
                new Productos().show();
                
                
            }
            catch(SQLException e){
                this.hide();
                new Productos().show();
            }
           
        }
       
     
    }//GEN-LAST:event_GuardarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.hide();
        new Productos().show();
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoProducto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JComboBox categoria;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox medida;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JComboBox proveedor;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
