/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GranEmpresa.Productos;
import java.sql.*;

import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author JenniferB
 */
public class Productos extends javax.swing.JFrame {
    Connection sesion;

    /**
     * Creates new form Productos
     */
    public static String ClaveProdActual=""; 
    public Productos() {
        initComponents();
        
        String ClaveProd;
        String Nombre;
        String Descripcion;
        float Precio;
        int Cantidad;
        String ClaveProv;
        String ClaveMed;
        String ClaveCat;
        String ClaveProdCat;
        
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            sesion=DriverManager.getConnection("jdbc:odbc:conectar");
           
            Connection sesion2;
            sesion2=DriverManager.getConnection("jdbc:odbc:conectar"); //Se realizan dos conexiones para acceder a la relacióm
            
          Statement sel= sesion.createStatement();
          Statement sel2= sesion2.createStatement();
          
          ResultSet temprel;
          
          ResultSet rpt= sel.executeQuery("SELECT * FROM Productos");
          while(rpt.next()){//Se leerán mientras existan registros siguientes
            //Se leen en variables los campos de la tabla
            ClaveProd=rpt.getString(1);
            Nombre=rpt.getString(2);
            Descripcion=rpt.getString(3);
            Precio=rpt.getFloat(4);
            Cantidad=rpt.getInt(5);
            ClaveProv=rpt.getString(6);
            ClaveMed=rpt.getString(7);
            ClaveCat=rpt.getString(8);
            ClaveProdCat=rpt.getString(9);
            //Se agregan de manera cíclica los registros a un modelo
            //Dicho modelo se cargara en la tabla por cada registro.
            
            String MEDIDA="";//SE NECESITA OBTENER EL NOMBRE DE LA MEDIDA POR MEDIO DE LA RELACIÓN
            String PROVEEDOR="";//SE NECESITA OBTENER EL NOMBRE DEL PROVEEDOR POR MEDIO DE LA RELACIÓN
            String CATEGORIA="";//SE NECESITA OBTENER EL NOMBRE DE LA CATEGORÍA POR MEDIO DE LA RELACIÓN
            
            temprel= sel2.executeQuery("SELECT * FROM Proveedores WHERE ClaveProv='"+ClaveProv+"'"); 
            temprel.next();
            PROVEEDOR=temprel.getString(2);
          
            temprel= sel2.executeQuery("SELECT * FROM Medidas WHERE ClaveMed='"+ClaveMed+"'"); 
            temprel.next();
            MEDIDA=temprel.getString(2);
           
            temprel= sel2.executeQuery("SELECT * FROM Categorias WHERE ClaveCat='"+ClaveCat+"'");   
            temprel.next();
            CATEGORIA=temprel.getString(2);
            temprel.close();
            
            DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
            modelo.addRow(new Object[]{ClaveProdCat,Nombre,Descripcion,Precio,Cantidad,MEDIDA,CATEGORIA,PROVEEDOR});
            
          }
          rpt.close();
        }
        catch(ClassNotFoundException | SQLException e){
           JOptionPane.showMessageDialog(this, "ERROR AL OBTENER DATOS DE LOS PRODUCTOS");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fecha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Buscar = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        Fecha.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Fecha.setForeground(new java.awt.Color(0, 0, 255));
        Fecha.setText("Productos");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/nuevo.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/modificar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/borrar.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/regresar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Nombre", "Descripción", "Precio", "Cantidad", "Medida", "Categoría", "Proveedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GranEmpresa/img/Buscar.png"))); // NOI18N
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton3)
                        .addGap(44, 44, 44)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 252, Short.MAX_VALUE)
                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Fecha)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.hide();
        new NuevoProducto().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int i=0;
       i = jTable1.getSelectedRow();
       if (i==-1){
           JOptionPane.showMessageDialog(null,"Debe seleccionar una fila");
           jTable1.requestFocus();
       }else{
           ClaveProdActual=jTable1.getValueAt(i, 0).toString(); 
           this.hide();
           new ModificarProducto().show();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        this.hide();
        new BuscarProducto().show();
    }//GEN-LAST:event_BuscarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int i=0;
       i = jTable1.getSelectedRow();
       if (i==-1){
           JOptionPane.showMessageDialog(null,"Debe seleccionar una fila");
           jTable1.requestFocus();
       }else{
           int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea borrar éste registro?");
           if(confirm==0){
               String ElementoBorrado=jTable1.getValueAt(i, 0).toString();
               try{
                sesion=DriverManager.getConnection("jdbc:odbc:conectar");     
                Statement sel= sesion.createStatement();
                ResultSet rpt= sel.executeQuery("DELETE FROM Productos WHERE ClaveProdCat='"+ElementoBorrado+"'");
                rpt.next();
                JOptionPane.showMessageDialog(null,"Datos eliminados");
                this.hide();
                new Productos().show();
               }
               catch(SQLException e){
                   this.hide();
                   new Productos().show();
               }
           }
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
